# mydevsandbox.com

title: MyDevSandbox
# email:
description: |
  Playground space for working with code examples and mock-ups.
baseurl: ""
url: "https://mydevsandbox.com"
# twitter_username:
github_username: mydevsandbox-com
copyright: mydevsandbox.com 2022

# theme:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .ruby*
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME
